#!/bin/sh

size=$(hyprctl activewindow | grep size: | cut -d' ' -f2)
width=$(echo $size | cut -d',' -f1)
height=$(echo $size | cut -d',' -f2)

if [ $1 = left ]; then
  width=$((width / 2))
elif [ $1 = right ]; then
  width=$((width * 2))
elif [ $1 = up ]; then
  height=$((height / 2))
elif [ $1 = down ]; then
  height=$((height * 2))
fi

echo $width $height
hyprctl dispatch resizeactive exact $width $height
