#!/bin/sh

current_workspace=$(hyprctl activeworkspace | grep 'workspace ID' | head -n1 | sd 'workspace ID .* \((.*)\).*' '$1')
hyprctl dispatch movetoworkspacesilent $1
sleep 1
~/.config/hypr/scripts/tile-active-workspace $current_workspace
~/.config/hypr/scripts/tile-active-workspace $1
